Make sure the buildpack detects only deploys with SSH keys
--Tim Shadel <tim.shadel@familysearch.org>

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,15 +1,9 @@
-# #!/usr/bin/env ruby
+#!/usr/bin/env bash
 
-# $:.unshift File.expand_path("../../lib", __FILE__)
-# require "buildpack"
-
-# if pack = BuildPack.detect(ARGV.first)
-#   puts pack.name
-#   exit 0
-# else
-#   puts "no"
-#   exit 1
-# end
-
-echo "Private SSH Keys"
-exit 0
+if [ -f $1/deploy/id_rsa ]; then
+  echo "Private SSH Keys"
+  exit 0
+else
+  echo "Can't find the ssh key file"
+  exit 1
+fi
