Print out key fingerprint, require known_hosts
--Tim Shadel <tim.shadel@familysearch.org>

Signed-off-by: Tim Shadel <tim.shadel@familysearch.org>

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,8 +1,15 @@
 #!/usr/bin/env bash
 
 if [ -f $1/deploy/id_rsa ]; then
-  echo "Private SSH Keys"
-  exit 0
+
+  if [ -f $1/deploy/known_hosts ]; then
+    echo "Private SSH Keys"
+    exit 0
+  else
+    echo "Can't find the known hosts file"
+    exit 1
+  fi
+
 else
   echo "Can't find the ssh key file"
   exit 1
